import { PracticalCriterion, TrainingModule, TrainingTrack } from '../types';

const BOTH = ['SFD', 'B6'];
const criteria = (names: string[], critical: string[] = []): PracticalCriterion[] => names.map((name, index) => ({ id: `criterion-${index + 1}`, name, isCritical: critical.includes(name), scored: true, weight: 1 }));
const training = (title: string, track: TrainingTrack, outlets: string[], roles: string[], instructions: string, practical: string[], critical: string[] = [], options: Partial<TrainingModule> = {}): TrainingModule => ({
  title, track, applicableOutletIds: outlets, applicableRoles: roles, description: title, learningObjectives: [], estimatedMinutes: 30, mandatory: true, instructions, media: [], safetyWarnings: critical, relatedRecipeIds: [], relatedEquipment: [], relatedTaskIds: [],
  lessons: [
    { id: 'knowledge', type: 'KNOWLEDGE', title: 'Learn the Green Neko standard', content: instructions, required: true },
    { id: 'demonstration', type: 'DEMONSTRATION', title: 'Trainer demonstration', checklist: practical, required: true },
    { id: 'practice', type: 'SUPERVISED_PRACTICE', title: 'Supervised practice', checklist: practical, required: true },
    { id: 'practical', type: 'PRACTICAL_ASSESSMENT', title: 'Practical assessment', checklist: practical, required: true },
  ], requiredLessonOrder: true, requiredSupervisedAttempts: 1, knowledgeTestRequired: true, practicalTestRequired: true, minimumPassingScore: 80, quizQuestions: [], quizAttemptLimit: 2, practicalCriteria: criteria(practical, critical), managerSignOffRequired: true, certificationValidityDays: 365, version: 1, status: 'DRAFT', updateRequirement: 'NONE', changeSummary: 'Green Neko Staff & Manager Training Plan', ...options,
});

export const trainingStarterTemplates: TrainingModule[] = [
  training('Green Neko orientation', 'CORE_STAFF', BOTH, [], `Understand Green Neko, its menu, service style, outlets and operating standards.\n\nSafdarjung/94A (SFD) is the express, beverage-led format: boba, matcha, coffee and limited food. Deer Park/B6 is the experience format: full food and beverage menu including ramen, poke, donburi, appetisers, drinks and desserts. Staff are trained and assessed only on products used at their own outlet.\n\nEmployee must explain what Green Neko serves, their outlet format, the difference between formats, and their responsibilities.`, ['Explain Green Neko concept', 'Explain assigned outlet format', 'Explain role responsibilities']),
  training('Basic attitude and work standards', 'CORE_STAFF', BOTH, [], `Green Neko standards are Clean, Fast, Friendly, Responsible and Consistent. Keep work areas clean throughout the shift; work with urgency without sacrificing safety; acknowledge customers politely; complete Neko Pulse tasks and report mistakes, shortages, damage and safety concerns; follow approved recipes and service methods without guessing.`, ['Personal presentation', 'Punctuality', 'Communication', 'Speed with quality', 'Cleanliness', 'Task completion', 'Teamwork', 'Responsibility']),
  training('Personal hygiene and food safety', 'CORE_STAFF', BOTH, [], `Arrive in a clean complete uniform. Restrain hair and maintain suitable nails. Wash hands before work and after waste, phones, money, raw products or unclean surfaces. Report illness. Use clean utensils and designated equipment. Prevent vegetarian/non-vegetarian and raw/ready-to-eat cross-contamination. Follow labels, dates and approved storage standards; report expired, damaged, contaminated or doubtful products.`, ['Correct handwashing', 'Correct glove use', 'Safe food storage', 'Cross-contamination prevention', 'Cleaning and sanitising procedure'], ['Correct handwashing', 'Safe food storage', 'Cross-contamination prevention', 'Cleaning and sanitising procedure'], { certificationValidityDays: 180 }),
  training('Customer service, complaints and mistakes', 'CORE_STAFF', BOTH, [], `Acknowledge customers promptly: “Hello! Welcome to Green Neko. What can I get for you today?” Listen without interrupting; capture every item and customisation; repeat the full order; confirm dine-in/takeaway, amount, payment and an honest preparation time. Recommend without pressure and never guess allergen information.\n\nUse LISTEN for complaints: Listen, Identify, Say sorry, Take action, Escalate, Note. Escalate refunds, allergies/food safety, unresolved dissatisfaction, staff-behaviour concerns, uncertainty and aggressive situations. Admit mistakes promptly, correct them, record wastage/remakes and never blame colleagues in front of customers.`, ['Greeting role-play', 'Order-taking role-play', 'Menu recommendation', 'Incorrect-order recovery', 'Complaint escalation']),
  training('Outlet-specific menu knowledge', 'CORE_STAFF', BOTH, [], `Study and certify only products active at the assigned outlet. For each product know its name, category, main ingredients, taste/texture, vegetarian or non-vegetarian status, approved allergen information, portion/quantity, preparation, preparation time, presentation, allowed customisations and correct POS price. Never guess allergy information; use the approved guide or ask the chef/manager.`, ['Identify assigned products', 'Explain product to a customer', 'Recommend suitable products', 'Find verified allergen information', 'Prepare assigned product where applicable']),

  training('Bar setup and opening', 'BARISTA', BOTH, ['Barista'], `Start the POS, log into Neko Pulse, review assigned tasks, switch on approved equipment safely, check the coffee machine, ingredients, milk, syrups, boba, cups, lids and ice. Clean and sanitise the bar, prepare the workstation and report shortages. Daily opening execution remains in the existing Neko Pulse task checklist.`, ['Safe equipment start-up', 'Coffee-machine check', 'Ingredient readiness', 'Sanitised workstation', 'Shortage reporting']),
  training('Coffee-machine operation', 'BARISTA', BOTH, ['Barista'], `Follow safe startup and shutdown, espresso extraction standard, milk steaming and approved drink assembly. Prevent cross-contact. Clean the steam wand and group head, complete daily machine cleaning and report problems.`, ['Safe startup/shutdown', 'Espresso extraction', 'Milk steaming', 'Steam-wand cleaning', 'Group-head cleaning', 'Machine-problem reporting'], ['Safe startup/shutdown', 'Steam-wand cleaning']),
  training('Standard drink preparation', 'BARISTA', BOTH, ['Barista'], `Use approved coffee, matcha and boba recipes. Measure syrups, ice, sugar, milk, alternatives and toppings with approved tools. Follow cup presentation and approved customisations. Free pouring or guessing is never permitted unless an approved recipe explicitly allows it.`, ['Recipe accuracy', 'Measurement accuracy', 'Preparation sequence', 'Temperature and taste', 'Cup presentation', 'Workstation hygiene'], ['Recipe accuracy', 'Measurement accuracy']),
  training('Barista customer service', 'BARISTA', BOTH, ['Barista'], `Apply Green Neko customer-service standards at the bar: greet, explain the menu, recommend, confirm customisations, repeat orders, manage preparation-time expectations, handle complaints and call a manager where needed.`, ['Greeting', 'Recommendation', 'Customised order confirmation', 'Incorrect-order recovery', 'Complaint handling']),
  training('Bar cleaning and sanitation', 'BARISTA', BOTH, ['Barista'], `Clean-as-you-go is mandatory. Maintain counters, equipment, fridges/storage, customer-facing areas and waste disposal. Complete closing sanitation using the existing Neko Pulse closing tasks.`, ['Counter cleaning', 'Equipment cleaning', 'Fridge/storage organisation', 'Customer-facing dusting', 'Waste disposal', 'Closing sanitation'], ['Equipment cleaning', 'Closing sanitation']),

  training('Kitchen safety', 'KITCHEN', ['B6'], ['Kitchen'], `Kitchen safety is mandatory before independent food preparation: handwashing, uniform/PPE, knife safety, hot-equipment safety, spill/burn response, chemical storage, fire awareness and injury reporting.`, ['Handwashing', 'PPE/uniform', 'Knife handling', 'Hot-equipment safety', 'Spill/burn response', 'Chemical storage'], ['Handwashing', 'Knife handling', 'Hot-equipment safety', 'Chemical storage'], { certificationValidityDays: 180 }),
  training('Kitchen cross-contamination prevention', 'KITCHEN', ['B6'], ['Kitchen'], `Separate vegetarian and non-vegetarian preparation, designated utensils and storage; separate raw and ready-to-eat products; clean and sanitise between tasks; store allergens under the approved system; never reuse a dropped or contaminated utensil without washing and sanitising it.`, ['Vegetarian/non-vegetarian separation', 'Raw/ready-to-eat separation', 'Utensil control', 'Sanitising between tasks', 'Allergen storage'], ['Vegetarian/non-vegetarian separation', 'Raw/ready-to-eat separation', 'Sanitising between tasks'], { certificationValidityDays: 180 }),
  training('Kitchen storage checks and FIFO', 'KITCHEN', ['B6'], ['Kitchen'], `Check product name, prepared/opening date, use-by date, new and old stock, FIFO rotation, storage condition, packaging, approved temperature and vegetarian/non-vegetarian separation. Isolate and report unsafe or doubtful products.`, ['Label check', 'Date check', 'FIFO rotation', 'Storage condition', 'Temperature check', 'Unsafe-product escalation'], ['FIFO rotation', 'Unsafe-product escalation'], { certificationValidityDays: 180 }),
  training('Kitchen stock responsibilities', 'KITCHEN', ['B6'], ['Kitchen'], `Check required stock before service. Inform the manager about low or missing stock, record wastage, avoid unauthorised substitutions, never hide shortages and help complete scheduled stock counts.`, ['Pre-service stock check', 'Low-stock report', 'Wastage record', 'Authorised-substitution check']),
  training('Kitchen daily preparation and tasting', 'KITCHEN', ['B6'], ['Kitchen'], `Before service, inspect sauces and prepared ingredients for colour, smell, texture, date and storage; prepare vegetables to specification; complete designated daily tasting and record it in Neko Pulse; escalate any failed product immediately.`, ['Ingredient inspection', 'Vegetable preparation', 'Daily tasting', 'Neko Pulse tasting record', 'Failure escalation'], ['Ingredient inspection', 'Failure escalation']),
  training('Kitchen recipe compliance', 'KITCHEN', ['B6'], ['Kitchen'], `For every assigned menu item follow ingredients, exact quantities, sequence, cooking temperature, preparation time, plating, holding limit, allergen information, storage and wastage procedure. Changes require authorised approval.`, ['Ingredient selection', 'Exact measurement', 'Preparation sequence', 'Cooking temperature', 'Taste and texture', 'Plating', 'Cleaning after preparation'], ['Exact measurement', 'Cooking temperature', 'Cross-contamination control'], { certificationValidityDays: 180 }),

  training('Leading a shift', 'MANAGER', BOTH, ['Manager'], `A Green Neko manager must understand both the kitchen and barista stations well enough to run the outlet safely, even when a team member is absent. Start every shift by checking attendance, lateness, staffing gaps and the service plan. Allocate clear stations and Neko Pulse tasks; give a short briefing covering sales focus, priorities, safety, shortages and expected rush periods.

During service, move between front counter, bar and kitchen. Keep the team organised, calm and helpful; resolve staff conflicts privately and fairly; support staff during rush rather than only giving instructions. Give clear, respectful direction—never shout, insult or embarrass anyone. Escalate operational problems early and record relevant actions in the handover. Daily opening and closing execution stays in the existing Neko Pulse task system.`, ['Attendance and lateness review', 'Station allocation for bar, kitchen and counter', 'Pre-shift team briefing', 'Both-station readiness inspection', 'Rush-period deployment', 'Staff-conflict resolution', 'Operational escalation and handover']),
  training('Training employees', 'MANAGER', BOTH, ['Manager'], `Managers build capable teams: explain the standard, demonstrate the job, allow supervised practice, observe the employee doing the work, give precise coaching and assess only genuine competence. This applies to bar, kitchen, POS, service and safety standards.

Use the training record to document the demonstration, attempts, feedback and evidence. A manager may not certify themselves. Never pass or certify someone merely because they attended training, are a friend, or the outlet is busy. Unsafe work, repeated standards failures or critical food-safety failures require retraining and reassessment.`, ['Explain the required standard', 'Demonstrate a station task', 'Observe supervised practice', 'Give specific coaching notes', 'Record evidence and results', 'Set retraining action where required', 'Use certification authority correctly']),
  training('Daily quality control', 'MANAGER', BOTH, ['Manager'], `The manager is the outlet’s standards representative. Inspect kitchen, bar, counter and customer areas throughout the shift—not only at opening or closing. Check uniforms, handwashing, kitchen cleanliness, bar cleanliness, equipment condition, safe storage, labels, vegetarian/non-vegetarian separation, recipe accuracy, portion and presentation standards.

Taste key products at least once or twice each month and whenever a quality concern is raised; record the check and corrective action. Confirm that equipment issues from both stations are logged and escalated, pest-control checks are completed when due, and required operational checks are added to Task Manager.`, ['Kitchen-cleanliness inspection', 'Bar and counter-cleanliness inspection', 'Storage, date-label and separation check', 'Equipment condition update from kitchen and bar', 'Recipe, portion and presentation observation', 'Product-tasting record', 'Pest-control and Task Manager review'], ['Kitchen-cleanliness inspection', 'Bar and counter-cleanliness inspection', 'Storage, date-label and separation check']),
  training('Complaint escalation', 'MANAGER', BOTH, ['Manager'], `Handle every complaint calmly and with a genuine smile. Listen without interrupting, thank the customer for raising it, confirm the facts, apologise when Green Neko has made a mistake and give a clear solution. Do not argue, blame staff, promise what you cannot deliver or discuss a colleague in front of the customer.

Managers control permitted remakes, refunds and recoveries. Verify the order and payment first, ensure a safe and correctly made replacement where needed, log the refund/remake and related wastage, then follow up with the team privately. Escalate food safety, allergy, injury, harassment, serious conflict or unresolved complaints immediately.`, ['Calm complaint conversation', 'Order and payment verification', 'Permitted remake or refund decision', 'Accurate refund/remake/wastage record', 'Serious-incident escalation', 'Private team follow-up', 'Retraining decision after repeated error']),
  training('Coaching and feedback', 'MANAGER', BOTH, ['Manager'], `Managers are helpful to everyone: staff and customers. Correct unsafe or disrespectful behaviour immediately; otherwise give feedback privately, using the observed behaviour, the Green Neko standard, the impact and the next action. Handle lateness and conflict consistently, listen to both sides and document the agreed action when it affects operations.

During rush, give short clear commands: who owns each station, what comes first and when to ask for help. Balance accountability with support—step in where needed, recognise good work and ensure no one is left without direction.`, ['Immediate unsafe-behaviour correction', 'Private performance conversation', 'Lateness discussion and action', 'Staff-conflict resolution', 'Clear rush-period direction', 'Positive recognition', 'Documented retraining or follow-up plan']),
  training('Stock and operational control', 'MANAGER', BOTH, ['Manager'], `Run the store with control over stock, cash, equipment and delivery orders. Before and during service, confirm the POS counter is opened correctly, cash is secured and handled under the approved process, and the team knows how to report discrepancies. Check that Zomato and Swiggy orders are accepted, prepared, packed, marked correctly and handed over on time.

Review stock readiness, FIFO, shortages, recipe and portion control, and wastage from both kitchen and bar. Investigate unusual waste, repeated remakes, missing items and discount use. Capture equipment updates from both stations and escalate breakdowns before they disrupt service.`, ['POS opening check', 'Cash-control check', 'Zomato/Swiggy order monitoring', 'Kitchen and bar stock readiness', 'FIFO and shortage review', 'Wastage and remake investigation', 'Discount review', 'Equipment issue escalation']),
  training('Manager shift leadership certification', 'MANAGER', BOTH, ['Manager'], `This is the final supervised practical assessment for a manager. Lead a complete shift across both stations: review attendance and lateness; assign stations; brief the team; inspect kitchen, bar, counter and customer areas; run the POS opening and cash-control check; monitor Zomato/Swiggy orders; manage a rush; resolve an operational issue; coach a team member; and handle a customer complaint or simulated recovery.

Before closing, review sales, expenses, cost basics, discounts and wastage; verify closing standards and required Neko Pulse tasks; then post a clear closing and handover report in the operations group. The manager must demonstrate helpful, calm leadership and correct escalation. Certification requires an owner, operations lead or authorised senior manager—not self-certification.`, ['Attendance, lateness and staffing review', 'Station allocation and team briefing', 'Kitchen, bar, counter and cleanliness inspection', 'POS opening and cash-control check', 'Zomato/Swiggy order monitoring', 'Rush-period leadership', 'Operational-problem resolution', 'Staff coaching and conflict handling', 'Customer complaint recovery', 'Sales, expenses, discount and wastage review', 'Closing report and operations-group handover', 'Required Neko Pulse task closure'], ['Kitchen, bar, counter and cleanliness inspection', 'POS opening and cash-control check', 'Closing report and operations-group handover']),
];
