import React from 'react';
import { ArrowRight, CalendarClock, CheckCircle2, ClipboardCheck, GraduationCap, ShieldCheck, UsersRound } from 'lucide-react';

const trialUrl = `${window.location.pathname}?trial=1`;

export const NekoPulseMarketingView: React.FC = () => <main className="min-h-screen bg-[#f7f5ef] text-[#123229] selection:bg-[#b9ddc8]">
  <header className="max-w-6xl mx-auto px-5 py-5 flex items-center justify-between border-b border-[#ded9ce]/80"><a href="#top" className="font-semibold tracking-tight text-lg">◒ NEKO PULSE</a><nav className="hidden sm:flex gap-6 text-sm font-medium text-slate-600"><a href="#product">Product</a><a href="#why">Why Pulse</a><a href="#faq">FAQ</a></nav><a href="#trial" className="rounded-full bg-[#063b2c] text-white px-4 py-2 text-sm font-semibold">Start free</a></header>
  <section id="top" className="max-w-6xl mx-auto px-5 pt-16 md:pt-24 pb-16 grid lg:grid-cols-[1fr_.9fr] gap-12 items-center"><div><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">RESTAURANT OPERATIONS, IN RHYTHM</p><h1 className="mt-5 text-5xl md:text-7xl leading-[.95] font-semibold tracking-tight">A calmer way<br/>to run every shift.</h1><p className="mt-6 max-w-xl text-lg text-slate-600 leading-relaxed">Neko Pulse gives cafés and restaurants one clear place for attendance, team tasks, shift planning, training and daily accountability.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#trial" className="inline-flex items-center gap-2 rounded-full bg-[#063b2c] text-white px-5 py-3 font-semibold">Try it free for 30 days <ArrowRight className="w-4 h-4"/></a><a href="#product" className="inline-flex items-center gap-2 rounded-full border border-[#bdb8ac] px-5 py-3 font-semibold">See how it works ↓</a></div><p className="mt-4 text-sm text-slate-500">No card required · Set up your first outlet in minutes</p></div><PulsePreview /></section>
  <div className="border-y border-[#ded9ce] py-4 text-center text-xs font-bold tracking-[.16em] text-[#426056]">ONE OPERATING PICTURE · PEOPLE · TASKS · SHIFTS · TRAINING · ATTENDANCE · MULTI-OUTLET</div>
  <section id="product" className="max-w-6xl mx-auto px-5 py-20"><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">MADE FOR THE REAL DAY</p><h2 className="mt-4 text-4xl md:text-5xl font-semibold tracking-tight">Less chasing.<br/>More confidence.</h2><p className="mt-5 max-w-2xl text-slate-600 text-lg">The operational details that often live in WhatsApp, paper lists and memory become clear, assigned and visible.</p><div id="why" className="mt-12 grid md:grid-cols-3 gap-4"><Feature number="01" icon={<ClipboardCheck/>} title="Every task has an owner" text="Give teams clear work, proof where needed, and a shared view of what is still open."/><Feature number="02" icon={<CalendarClock/>} title="The shift stays in control" text="Plan the service day, see attendance, and keep managers focused on what needs attention."/><Feature number="03" icon={<GraduationCap/>} title="Skills become visible" text="Assign learning, track practical progress and recognise certified competence—not just completed reading."/></div></section>
  <section className="bg-[#063b2c] text-white"><div className="max-w-6xl mx-auto px-5 py-20 grid md:grid-cols-2 gap-10"><div><p className="text-xs font-bold tracking-[.18em] text-[#b9ddc8]">BUILT FOR RESPONSIBLE OPERATIONS</p><h2 className="mt-4 text-4xl font-semibold leading-tight">A better shift feels different.</h2></div><div className="grid gap-5">{[[<UsersRound/>, 'A team that knows what good looks like'],[<CheckCircle2/>, 'Managers who can act before small issues become big ones'],[<ShieldCheck/>, 'A clear record without turning service into paperwork']].map(([icon, text], i) => <div key={i} className="flex gap-4 items-center border-b border-white/15 pb-5"><span className="text-[#b9ddc8]">{icon as any}</span><p className="text-lg">{text as string}</p></div>)}</div></div></section>
  <section id="trial" className="max-w-6xl mx-auto px-5 py-20 grid lg:grid-cols-[1fr_.8fr] gap-10"><div><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">YOUR FIRST MONTH IS ON US</p><h2 className="mt-4 text-5xl font-semibold tracking-tight">Give your<br/>operation a pulse.</h2><p className="mt-5 max-w-lg text-slate-600 text-lg">Use the complete system for 30 days. No card, no reduced trial mode and no automatic charge.</p><ul className="mt-7 space-y-3 text-slate-700"><li>✓ Attendance, tasks and shift planning</li><li>✓ Team, outlet and role management</li><li>✓ Training workspace and operational reporting</li></ul></div><div className="rounded-3xl bg-white p-7 shadow-[0_18px_42px_rgba(22,44,35,.1)] border border-[#e7e2d9]"><p className="text-xs font-bold tracking-[.16em] text-[#0b6b4d]">30 DAYS FREE</p><h3 className="mt-2 text-2xl font-semibold">Create your workspace.</h3><p className="mt-3 text-slate-600">Tell us about your first outlet, verify your email, and begin your trial.</p><a href={trialUrl} className="mt-6 inline-flex w-full justify-center items-center gap-2 rounded-xl bg-[#063b2c] text-white py-3 font-semibold">Start my free month <ArrowRight className="w-4 h-4"/></a><p className="text-xs text-slate-500 mt-4">By continuing, you agree to the Terms and Privacy Policy. We never charge during your trial.</p></div></section>
  <section id="faq" className="max-w-3xl mx-auto px-5 pb-24"><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">GOOD TO KNOW</p><h2 className="mt-3 text-4xl font-semibold">Questions, answered.</h2><div className="mt-8 space-y-4"><Faq q="Do I need a credit card?" a="No. Your trial starts without payment details and does not renew automatically."/><Faq q="What happens after 30 days?" a="You can choose a monthly or annual plan when subscriptions are enabled. Your data remains available while you decide."/><Faq q="Is Neko Pulse only for cafés?" a="No. It is built for hospitality teams that need smoother, more accountable daily operations."/></div></section>
  <footer className="border-t border-[#ded9ce] py-8 text-center text-sm text-slate-500">◒ NEKO PULSE · Built for restaurants that care about the details. © 2026</footer>
</main>;
const Feature = ({number, icon, title, text}: any) => <article className="rounded-2xl border border-[#ded9ce] bg-[#fffdf9] p-6"><p className="text-xs font-bold text-[#0b6b4d]">{number}</p><div className="mt-8 text-[#0b6b4d]">{icon}</div><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 text-slate-600">{text}</p></article>;
const Faq = ({q,a}: {q:string;a:string}) => <div className="border-b border-[#ded9ce] py-5"><h3 className="font-semibold text-lg">{q}</h3><p className="mt-2 text-slate-600">{a}</p></div>;
const PulsePreview = () => <div className="rounded-[2rem] bg-[#163e32] p-4 shadow-2xl rotate-1"><div className="rounded-[1.5rem] bg-[#f7f5ef] p-5"><div className="flex justify-between text-xs text-slate-500"><span>Tuesday · B6 Market</span><span className="text-[#0b6b4d] font-bold">LIVE DAY</span></div><h3 className="mt-5 text-2xl font-semibold">Today, in control.</h3><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#dcefe3] p-4"><p className="text-xs">Team checked in</p><p className="text-2xl font-semibold mt-2">8 / 9</p></div><div className="rounded-xl bg-[#f6e8cf] p-4"><p className="text-xs">Needs attention</p><p className="text-2xl font-semibold mt-2">3</p></div></div><div className="mt-4 rounded-xl border border-[#ded9ce] p-4"><p className="text-xs font-bold text-[#0b6b4d]">OPENING TASKS</p><p className="mt-2 font-semibold">Bar cleaning check</p><p className="text-sm text-slate-500">Assigned to Counter · due 10:30</p></div></div></div>;
