import React from 'react';
import { ArrowRight, CalendarClock, CheckCircle2, ClipboardCheck, FileText, GraduationCap, ScanLine, ShieldCheck, UsersRound } from 'lucide-react';

const trialUrl = `${window.location.pathname}?trial=1`;
const modules = [
  ['Daily tasks, done visibly', 'Assign work to counter, kitchen, bar or named crew. Staff see their own work; managers see what is open, late and complete.', ClipboardCheck],
  ['People and employee records', 'Create staff profiles, photos, roles, outlet assignments and the information managers need in one secure place.', UsersRound],
  ['Drag-and-drop shifts', 'Build shifts around your actual service rhythm and give every team member a clear personal schedule.', CalendarClock],
  ['Attendance and time clock', 'QR attendance with a dedicated counter kiosk. See who checked in, when, and the picture across your outlets.', ScanLine],
  ['Training that proves competence', 'Assign reading, local-language or English videos, and practical learning by person, role or outlet.', GraduationCap],
  ['Order accuracy before handover', 'Scan online orders, use a packing checklist, and confirm every item is present before delivery handover.', CheckCircle2],
  ['HR letters without waiting', 'Prepare joining, resignation, bank and other HR letters quickly from consistent templates.', FileText],
  ['Store, access and audit control', 'Manage outlets and store records; decide manager access; and review login activity.', ShieldCheck],
];
export const NekoPulseMarketingView: React.FC = () => <main className="min-h-screen bg-[#f7f5ef] text-[#123229]">
  <header className="max-w-6xl mx-auto px-5 py-5 flex items-center justify-between border-b border-[#ded9ce]"><a href="#top" className="font-semibold text-lg">◒ NEKO PULSE</a><nav className="hidden sm:flex gap-6 text-sm font-medium text-slate-600"><a href="#product">Product</a><a href="#modules">Modules</a><a href="#trial">Free trial</a></nav><a href="#trial" className="rounded-full bg-[#063b2c] text-white px-4 py-2 text-sm font-semibold">Start free</a></header>
  <section id="top" className="max-w-6xl mx-auto px-5 pt-16 md:pt-24 pb-16 grid lg:grid-cols-[1fr_.9fr] gap-12 items-center"><div><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">RESTAURANT OPERATIONS, IN RHYTHM</p><h1 className="mt-5 text-5xl md:text-7xl leading-[.95] font-semibold tracking-tight">One calm place<br/>to run the day.</h1><p className="mt-6 max-w-xl text-lg text-slate-600 leading-relaxed">Neko Pulse is the operating system for restaurant and café teams: daily work, people, shifts, attendance, training, standards and accountability—across one outlet or a growing chain.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#trial" className="inline-flex items-center gap-2 rounded-full bg-[#063b2c] text-white px-5 py-3 font-semibold">Try it free for 30 days <ArrowRight className="w-4 h-4"/></a><a href="#modules" className="rounded-full border border-[#bdb8ac] px-5 py-3 font-semibold">Explore every module ↓</a></div><p className="mt-4 text-sm text-slate-500">No card required · Your crew gets their own simple app</p></div><Preview /></section>
  <div className="border-y border-[#ded9ce] py-4 text-center text-xs font-bold tracking-[.16em] text-[#426056]">TASKS · PEOPLE · SHIFTS · ATTENDANCE · TRAINING · HR · STORES · ACCESS CONTROL</div>
  <section id="product" className="max-w-6xl mx-auto px-5 py-20"><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">BUILT FOR THE REAL SHIFT</p><h2 className="mt-4 text-4xl md:text-5xl font-semibold tracking-tight">Less chasing.<br/>More clarity.</h2><p className="mt-5 max-w-2xl text-slate-600 text-lg">Neko Pulse turns work that usually lives in WhatsApp, paper lists and memory into simple, assigned and visible operations.</p></section>
  <section id="modules" className="max-w-6xl mx-auto px-5 pb-20"><div className="grid md:grid-cols-2 gap-4">{modules.map(([title, text, Icon]: any, index) => <article key={title} className="rounded-2xl border border-[#ded9ce] bg-[#fffdf9] p-6"><p className="text-xs font-bold text-[#0b6b4d]">{String(index + 1).padStart(2, '0')}</p><Icon className="w-6 h-6 mt-8 text-[#0b6b4d]"/><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-2 text-slate-600 leading-relaxed">{text}</p></article>)}</div></section>
  <section className="bg-[#063b2c] text-white"><div className="max-w-6xl mx-auto px-5 py-16 grid md:grid-cols-2 gap-10"><div><p className="text-xs font-bold tracking-[.18em] text-[#b9ddc8]">DESIGNED FOR GROWING HOSPITALITY TEAMS</p><h2 className="mt-4 text-4xl font-semibold leading-tight">Your standards, visible every day.</h2></div><div className="space-y-4 text-lg text-[#e2f1e7]"><p>• Crews get only the work and information they need.</p><p>• Managers can run one or multiple outlets with clear permissions.</p><p>• Owners keep control of people, access, records and standards.</p><p>• System maintenance tools help manage retention and data costs.</p></div></div></section>
  <section id="trial" className="max-w-6xl mx-auto px-5 py-20 grid lg:grid-cols-[1fr_.8fr] gap-10"><div><p className="text-xs font-bold tracking-[.18em] text-[#0b6b4d]">YOUR FIRST MONTH IS ON US</p><h2 className="mt-4 text-5xl font-semibold tracking-tight">Give your<br/>operation a pulse.</h2><p className="mt-5 max-w-lg text-slate-600 text-lg">Use the full system for 30 days. No card, no reduced trial mode and no automatic charge.</p></div><div className="rounded-3xl bg-white p-7 shadow-xl border border-[#e7e2d9]"><p className="text-xs font-bold tracking-[.16em] text-[#0b6b4d]">30 DAYS FREE</p><h3 className="mt-2 text-2xl font-semibold">Create your workspace.</h3><p className="mt-3 text-slate-600">Set up your restaurant, first outlet and owner account in minutes.</p><a href={trialUrl} className="mt-6 inline-flex w-full justify-center items-center gap-2 rounded-xl bg-[#063b2c] text-white py-3 font-semibold">Start my free month <ArrowRight className="w-4 h-4"/></a><p className="text-xs text-slate-500 mt-4">We never charge you during your trial.</p></div></section>
  <footer className="border-t border-[#ded9ce] py-8 text-center text-sm text-slate-500">◒ NEKO PULSE · Built for restaurants that care about the details. © 2026</footer>
</main>;
const Preview = () => <div className="rounded-[2rem] bg-[#163e32] p-4 shadow-2xl rotate-1"><div className="rounded-[1.5rem] bg-[#f7f5ef] p-5"><div className="flex justify-between text-xs text-slate-500"><span>Tuesday · Main outlet</span><span className="text-[#0b6b4d] font-bold">LIVE DAY</span></div><h3 className="mt-5 text-2xl font-semibold">Today, in control.</h3><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#dcefe3] p-4"><p className="text-xs">Team checked in</p><p className="text-2xl font-semibold mt-2">8 / 9</p></div><div className="rounded-xl bg-[#f6e8cf] p-4"><p className="text-xs">Needs attention</p><p className="text-2xl font-semibold mt-2">3</p></div></div><div className="mt-4 rounded-xl border border-[#ded9ce] p-4"><p className="text-xs font-bold text-[#0b6b4d]">OPENING TASKS</p><p className="mt-2 font-semibold">Bar cleaning check</p><p className="text-sm text-slate-500">Assigned to Counter · due 10:30</p></div></div></div>;
